#!/usr/bin/env bash

git clone git@github.com:SexyC/my-vim-conf.git

if [ ! ${HOME} ]; then
	echo "failure, HOME env not set"
	exit -1
fi

if [ -f ${HOME}/.vimrc ]; then
	if [ ! -f ${HOME}/.vimrc.back ]; then
		mv ${HOME}/.vimrc	${HOME}/.vimrc.back
	fi
	cp my-vim-conf/.vimrc ${HOME}/.vimrc
fi

if [ -d {$HOME}/.vim ]; then
	if [ ! -d ${HOME}/.vim.back]; then
		mv ${HOME}.vim   ${HOME}/.vim/back
	fi
	cp -r my-vim-conf/  ${HOME}/.vim
fi

