#!/usr/bin/env bash

if [ -d my-vim-conf ]; then
	echo "failure, already have my-vim-conf directory on the current directory"
	exit -1
fi

git clone https://github.com/SexyC/my-vim-conf.git

if [ ! ${HOME} ]; then
	echo "failure, HOME env not set"
	exit -1
fi

if [ -f ${HOME}/.vimrc ]; then
	if [ ! -f ${HOME}/.vimrc.back ]; then
		mv ${HOME}/.vimrc	${HOME}/.vimrc.back
	fi
fi
cp my-vim-conf/.vimrc ${HOME}/.vimrc

if [ -d {$HOME}/.vim ]; then
	if [ ! -d ${HOME}/.vim.back]; then
		mv ${HOME}/.vim   ${HOME}/.vim/back
	fi
	rm -rf ${HOME}/.vim
fi
cp -rf my-vim-conf/  ${HOME}/.vim

