#!/usr/bin/env bash

if [ -d ${HOME}/my-vim-conf ]; then
	echo "failure, already have my-vim-conf directory on the home directory"
	exit -1
fi

cd
git clone https://github.com/SexyC/my-vim-conf.git ${HOME}

if [ ! ${HOME} ]; then
	echo "failure, HOME env not set"
	exit -1
fi

if [ -f ${HOME}/.vimrc ]; then
	echo "Warning: original vimrc exist"
	if [ ! -f ${HOME}/.vimrc.back ]; then
		mv ${HOME}/.vimrc	${HOME}/.vimrc.back
	fi
fi
cp my-vim-conf/.vimrc ${HOME}/.vimrc

if [ -d ${HOME}/.vim ]; then
	echo "Warning: original .vim exist"
	if [ ! -d ${HOME}/.vim.back]; then
		mv ${HOME}/.vim   ${HOME}/.vim.back
	fi
	echo "Warning : delete original .vim"
	rm -rf ${HOME}/.vim
fi
cp -rf my-vim-conf/  ${HOME}/.vim

cd -

